# Generated by Django 3.2.13 on 2022-05-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_profiles_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
